enum BookType {
  genesis,
  exodus,
  leviticus,
  numbers,
  deuteronomy,
  joshua,
  judges,
  ruth,
  samuel1,
  samuel2,
  kings1,
  kings2,
  chronicles1,
  chronicles2,
  ezra,
  nehemiah,
  esther,
  job,
  psalms,
  proverbs,
  ecclesiastes,
  songOfSolomon,
  isaiah,
  jeremiah,
  lamentations,
  ezekiel,
  daniel,
  hosea,
  joel,
  amos,
  obadiah,
  jonah,
  micah,
  nahum,
  habakkuk,
  zephaniah,
  haggai,
  zechariah,
  malachi,
  matthew,
  mark,
  luke,
  john,
  acts,
  romans,
  corinthians1,
  corinthians2,
  galatians,
  ephesians,
  philippians,
  colossians,
  thessalonians1,
  thessalonians2,
  timothy1,
  timothy2,
  titus,
  philemon,
  hebrews,
  james,
  peter1,
  peter2,
  john1,
  john2,
  john3,
  jude,
  revelation;

  String title() => switch (this) {
    genesis => 'Genesis',
    exodus => 'Exodus',
    leviticus => 'Leviticus',
    numbers => 'Numbers',
    deuteronomy => 'Deuteronomy',
    joshua => 'Joshua',
    judges => 'Judges',
    ruth => 'Ruth',
    samuel1 => '1 Samuel',
    samuel2 => '2 Samuel',
    kings1 => '1 Kings',
    kings2 => '2 Kings',
    chronicles1 => '1 Chronicles',
    chronicles2 => '2 Chronicles',
    ezra => 'Ezra',
    nehemiah => 'Nehemiah',
    esther => 'Esther',
    job => 'Job',
    psalms => 'Psalms',
    proverbs => 'Proverbs',
    ecclesiastes => 'Ecclesiastes',
    songOfSolomon => 'Song of Solomon',
    isaiah => 'Isaiah',
    jeremiah => 'Jeremiah',
    lamentations => 'Lamentations',
    ezekiel => 'Ezekiel',
    daniel => 'Daniel',
    hosea => 'Hosea',
    joel => 'Joel',
    amos => 'Amos',
    obadiah => 'Obadiah',
    jonah => 'Jonah',
    micah => 'Micah',
    nahum => 'Nahum',
    habakkuk => 'Habakkuk',
    zephaniah => 'Zephaniah',
    haggai => 'Haggai',
    zechariah => 'Zechariah',
    malachi => 'Malachi',
    matthew => 'Matthew',
    mark => 'Mark',
    luke => 'Luke',
    john => 'John',
    acts => 'Acts',
    romans => 'Romans',
    corinthians1 => '1 Corinthians',
    corinthians2 => '2 Corinthians',
    galatians => 'Galatians',
    ephesians => 'Ephesians',
    philippians => 'Philippians',
    colossians => 'Colossians',
    thessalonians1 => '1 Thessalonians',
    thessalonians2 => '2 Thessalonians',
    timothy1 => '1 Timothy',
    timothy2 => '2 Timothy',
    titus => 'Titus',
    philemon => 'Philemon',
    hebrews => 'Hebrews',
    james => 'James',
    peter1 => '1 Peter',
    peter2 => '2 Peter',
    john1 => '1 John',
    john2 => '2 John',
    john3 => '3 John',
    jude => 'Jude',
    revelation => 'Revelation',
  };
}
